### ISSUE TITLE
Running Environment request

### ISSUE THREAD

**Issue by PetitBai** [pranav1601/Fire-Detection-Using-Deep-Learning-and-OpenCV#1]
Nice work!
To reproduce, could you pls list the running env, such as

* OS: [e.g. Linux Ubuntu 18.... LTS ]
* Tensorflow Version: [e.g. 1.x]
* OpenCV Version: [e.g. 3.4.x]
* etc...

**Comment by pranav1601** [comment]
Hey @PetitBai ,
Thanks for your feedback!
I have made the changes in the readme.
